package lv.pmeu.pmeu_sistema.shiftResult.model;

public enum ShiftResultCategory {
    IESNIEGUMS,
    APSTASANAS_STAVESANAS_NOTEIKUMI,
    RISKU_IZVERTESANA,
    LEMUMS_PAR_NOSKIRSANU,
    APAS_ALKOHOLA_LIETOSANA_ATRASANAS,
    APAS_MIERA_TRAUCESANA,
    APAS_CELU_SATIKSMES_LIKUMS,
    APAS_DZIVESVIETAS_DEKLARESANAS_LIKUMS,
    APAS_SMEKESANAS_NOTEIKUMU_NEIEVEROSANA,
    APAS_DZIVNIEKU_AIZSARDZIBAS_LIKUMS,
    APAS_SAISTOSO_NOTEIKUMU_IEVEROSANA,
    APAS_ATKRITUMU_APSAIMNIEKOSANAS_LIKUMS,
    APAS_BERNU_TIESIBU_AIZSARDZIBAS_LIKUMS,
    APAS_MAKSKERESANAS_NOTEIKUMU_IEVEROSANA,
    APAS_ATTEIKUMS_UZSAKT_PROCESU,
    APAS_UZDEVUMS_CITAI_IESTADEI,
    LICENCETAS_MAKSKERESANAS_PARBAUDE
}
