spring.application.name=PMEUUzskaitesSistema

spring.datasource.url=jdbc:mysql://localhost:3306/personala_mainu_uzskaite_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Riga
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

