spring.application.name=PMEUUzskaitesSistema

spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/personala_mainu_uzskaite_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Riga
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

