spring.application.name=PMEUUzskaitesSistema

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:create}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/personala_mainu_uzskaite_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Riga}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver